// price-manager.js - CARDIY App: Ket noi voi Google Sheet de lay bang gia va xuat bao cao
// Google Sheet ID: 1OTNA1wb6EoQ04uOa9nwXbnYsSSEEXzLb
// Apps Script Web App URL: cap nhat sau khi deploy

// === CAU HINH ===
// SAU KHI DEPLOY Apps Script, thay URL nay:
const SHEET_API_URL = 'REPLACE_WITH_APPS_SCRIPT_WEB_APP_URL';
const SHEET_ID = '1OTNA1wb6EoQ04uOa9nwXbnYsSSEEXzLb';

// === LAY BANG GIA TU GOOGLE SHEET ===
async function fetchBangGia() {
  try {
      if (!SHEET_API_URL || SHEET_API_URL === 'REPLACE_WITH_APPS_SCRIPT_WEB_APP_URL') {
            console.warn('CARDIY: Chua cai dat SHEET_API_URL');
                  return null;
                      }
                          const res = await fetch(SHEET_API_URL + '?action=prices');
                              const data = await res.json();
                                  if (data.success) {
                                        window.bangGiaCardiy = data.data;
                                              document.dispatchEvent(new CustomEvent('bangGiaLoaded', { detail: data }));
                                                    console.log('CARDIY: Da tai bang gia -', data.totalItems, 'dich vu');
                                                          return data.data;
                                                              }
                                                                } catch (err) {
                                                                    console.error('CARDIY: Loi tai bang gia:', err.message);
                                                                      }
                                                                        return null;
                                                                        }

                                                                        // === LAY GIA THEO MA DICH VU ===
                                                                        function getGiaTheoMa(maDichVu, loaiXe = 'sedan') {
                                                                          if (!window.bangGiaCardiy) return null;
                                                                            const item = window.bangGiaCardiy.find(p => p.maGia === maDichVu);
                                                                              if (!item) return null;
                                                                                return loaiXe.toLowerCase().includes('suv') ? item.giaSuv2 : item.giaSuv;
                                                                                }

                                                                                // === SYNC BOOKING TU FIREBASE → SHEET ===
                                                                                async function syncBookingToSheet(bookingData) {
                                                                                  try {
                                                                                      if (!SHEET_API_URL || SHEET_API_URL === 'REPLACE_WITH_APPS_SCRIPT_WEB_APP_URL') return false;
                                                                                          const res = await fetch(SHEET_API_URL, {
                                                                                                method: 'POST',
                                                                                                      headers: { 'Content-Type': 'application/json' },
                                                                                                            body: JSON.stringify({ action: 'sync_booking', data: bookingData })
                                                                                                                });
                                                                                                                    const result = await res.json();
                                                                                                                        if (result.success) {
                                                                                                                              console.log('CARDIY: Da sync booking vao Sheet:', bookingData.maJob);
                                                                                                                                    return true;
                                                                                                                                        }
                                                                                                                                          } catch (err) {
                                                                                                                                              console.error('CARDIY: Loi sync booking:', err.message);
                                                                                                                                                }
                                                                                                                                                  return false;
                                                                                                                                                  }
                                                                                                                                                  
                                                                                                                                                  // === CAP NHAT GIA TU APP → SHEET ===
                                                                                                                                                  async function updateGiaInSheet(maGia, newPrice, loaiXe = 'sedan') {
                                                                                                                                                    try {
                                                                                                                                                        if (!SHEET_API_URL || SHEET_API_URL === 'REPLACE_WITH_APPS_SCRIPT_WEB_APP_URL') return false;
                                                                                                                                                            const priceData = { maGia };
                                                                                                                                                                if (loaiXe.toLowerCase().includes('suv')) {
                                                                                                                                                                      priceData.giaSuv2 = newPrice;
                                                                                                                                                                          } else {
                                                                                                                                                                                priceData.giaSuv = newPrice;
                                                                                                                                                                                    }
                                                                                                                                                                                        const res = await fetch(SHEET_API_URL, {
                                                                                                                                                                                              method: 'POST',
                                                                                                                                                                                                    headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                          body: JSON.stringify({ action: 'update_price', data: priceData })
                                                                                                                                                                                                              });
                                                                                                                                                                                                                  const result = await res.json();
                                                                                                                                                                                                                      return result.success || false;
                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                            console.error('CARDIY: Loi cap nhat gia:', err.message);
                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                  // === XUAT BAO CAO EXCEL TU GOOGLE SHEET ===
                                                                                                                                                                                                                                  function exportExcelFromSheet(sheetName = 'all') {
                                                                                                                                                                                                                                    // Xuat truc tiep tu Google Sheets (khong can API)
                                                                                                                                                                                                                                      const exportUrls = {
                                                                                                                                                                                                                                          all: 'https://docs.google.com/spreadsheets/d/' + SHEET_ID + '/export?format=xlsx&title=CARDIY_BaoCao',
                                                                                                                                                                                                                                              nhatKyJob: 'https://docs.google.com/spreadsheets/d/' + SHEET_ID + '/export?format=xlsx&gid=297916355',
                                                                                                                                                                                                                                                  bangGia: 'https://docs.google.com/spreadsheets/d/' + SHEET_ID + '/export?format=xlsx&gid=1846730276',
                                                                                                                                                                                                                                                      baoCaoNgay: 'https://docs.google.com/spreadsheets/d/' + SHEET_ID + '/export?format=xlsx&gid=0'
                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                          const url = exportUrls[sheetName] || exportUrls.all;
                                                                                                                                                                                                                                                            const a = document.createElement('a');
                                                                                                                                                                                                                                                              a.href = url;
                                                                                                                                                                                                                                                                a.download = 'CARDIY_BaoCao_' + new Date().toLocaleDateString('vi-VN').replace(/\//g, '-') + '.xlsx';
                                                                                                                                                                                                                                                                  a.target = '_blank';
                                                                                                                                                                                                                                                                    document.body.appendChild(a);
                                                                                                                                                                                                                                                                      a.click();
                                                                                                                                                                                                                                                                        document.body.removeChild(a);
                                                                                                                                                                                                                                                                          console.log('CARDIY: Dang tai bao cao Excel tu Google Sheets...');
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                          // === XUAT BAO CAO TU FIREBASE (bookings) ===
                                                                                                                                                                                                                                                                          async function exportFirebaseReport() {
                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                const { getFirestore, collection, getDocs } = await import('https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js');
                                                                                                                                                                                                                                                                                    const db = getFirestore();
                                                                                                                                                                                                                                                                                        const snapshot = await getDocs(collection(db, 'bookings'));
                                                                                                                                                                                                                                                                                            const bookings = [];
                                                                                                                                                                                                                                                                                                snapshot.forEach(doc => { bookings.push({ id: doc.id, ...doc.data() }); });
                                                                                                                                                                                                                                                                                                    downloadAsExcel(bookings, 'CARDIY_Firebase_Bookings');
                                                                                                                                                                                                                                                                                                        console.log('CARDIY: Xuat', bookings.length, 'bookings tu Firebase');
                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                              console.error('CARDIY: Loi xuat Firebase report:', err);
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                // === TAO FILE CSV/EXCEL TU JAVASCRIPT ===
                                                                                                                                                                                                                                                                                                                function downloadAsExcel(data, filename = 'CARDIY_Report') {
                                                                                                                                                                                                                                                                                                                  if (!data || data.length === 0) {
                                                                                                                                                                                                                                                                                                                      alert('Khong co du lieu de xuat!');
                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                              const headers = Object.keys(data[0]);
                                                                                                                                                                                                                                                                                                                                const csvRows = [
                                                                                                                                                                                                                                                                                                                                    headers.join(','),
                                                                                                                                                                                                                                                                                                                                        ...data.map(row =>
                                                                                                                                                                                                                                                                                                                                              headers.map(h => {
                                                                                                                                                                                                                                                                                                                                                      const val = row[h] !== undefined ? String(row[h]) : '';
                                                                                                                                                                                                                                                                                                                                                              return '"' + val.replace(/"/g, '""') + '"';
                                                                                                                                                                                                                                                                                                                                                                    }).join(',')
                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                          ];
                                                                                                                                                                                                                                                                                                                                                                            const csvContent = '\uFEFF' + csvRows.join('\n'); // BOM for UTF-8
                                                                                                                                                                                                                                                                                                                                                                              const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
                                                                                                                                                                                                                                                                                                                                                                                const url = URL.createObjectURL(blob);
                                                                                                                                                                                                                                                                                                                                                                                  const a = document.createElement('a');
                                                                                                                                                                                                                                                                                                                                                                                    a.href = url;
                                                                                                                                                                                                                                                                                                                                                                                      a.download = filename + '_' + new Date().toLocaleDateString('vi-VN').replace(/\//g, '-') + '.csv';
                                                                                                                                                                                                                                                                                                                                                                                        document.body.appendChild(a);
                                                                                                                                                                                                                                                                                                                                                                                          a.click();
                                                                                                                                                                                                                                                                                                                                                                                            document.body.removeChild(a);
                                                                                                                                                                                                                                                                                                                                                                                              URL.revokeObjectURL(url);
                                                                                                                                                                                                                                                                                                                                                                                                console.log('CARDIY: Xuat', data.length, 'dong vao file Excel/CSV');
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                // === KHOI DONG: Tu dong tai bang gia khi app load ===
                                                                                                                                                                                                                                                                                                                                                                                                document.addEventListener('authReady', () => {
                                                                                                                                                                                                                                                                                                                                                                                                  fetchBangGia();
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                  // Export cac ham ra global
                                                                                                                                                                                                                                                                                                                                                                                                  window.CARDIY_PriceManager = {
                                                                                                                                                                                                                                                                                                                                                                                                    fetchBangGia,
                                                                                                                                                                                                                                                                                                                                                                                                      getGiaTheoMa,
                                                                                                                                                                                                                                                                                                                                                                                                        syncBookingToSheet,
                                                                                                                                                                                                                                                                                                                                                                                                          updateGiaInSheet,
                                                                                                                                                                                                                                                                                                                                                                                                            exportExcelFromSheet,
                                                                                                                                                                                                                                                                                                                                                                                                              exportFirebaseReport,
                                                                                                                                                                                                                                                                                                                                                                                                                downloadAsExcel,
                                                                                                                                                                                                                                                                                                                                                                                                                  SHEET_API_URL,
                                                                                                                                                                                                                                                                                                                                                                                                                    SHEET_ID
                                                                                                                                                                                                                                                                                                                                                                                                                    };
